import os
import sys
import struct

def pack_fs(programs_dir, out_file):
    dir_sector = bytearray(512)
    entries = []
    
    if not os.path.exists(programs_dir):
        print(f"Error: Programs directory '{programs_dir}' does not exist.")
        sys.exit(1)
        
    files = sorted([f for f in os.listdir(programs_dir) if f.endswith('.easec')])
    files = files[:10]
    
    current_relative_sector = 1
    file_data_blocks = bytearray()
    
    for filename in files:
        filepath = os.path.join(programs_dir, filename)
        with open(filepath, 'rb') as f:
            data = f.read()
            
        size = len(data)
        num_sectors = (size + 511) // 512
        if num_sectors == 0:
            num_sectors = 1
            
        absolute_start_sector = 256 + current_relative_sector

        entry_bytes = struct.pack('<32sIIIB3x', 
                                  filename.encode('utf-8')[:31], 
                                  absolute_start_sector, 
                                  num_sectors, 
                                  size, 
                                  1)
        entries.append(entry_bytes)
        
        padded_data = bytearray(data)
        padding_needed = (512 - (len(padded_data) % 512)) % 512
        padded_data.extend(b'\x00' * padding_needed)
        
        file_data_blocks.extend(padded_data)
        current_relative_sector += num_sectors

    for i, entry in enumerate(entries):
        offset = i * 48
        dir_sector[offset:offset+48] = entry
        
    dir_sector[508:512] = b'INST'
        
    with open(out_file, 'wb') as out:
        out.write(dir_sector)
        out.write(file_data_blocks)
        
    print(f"Packed {len(files)} files into {out_file}.")

    with open('kernel/fs_bin.h', 'w') as f:
        f.write("/* Auto-generated by pack_fs.py */\n")
        f.write("#ifndef FS_BIN_H\n#define FS_BIN_H\n\n")
        f.write("static const unsigned char fs_bin[] = {\n")
        with open(out_file, 'rb') as fs:
            data = fs.read()
        for idx, val in enumerate(data):
            f.write(f"0x{val:02x}, ")
            if (idx + 1) % 12 == 0:
                f.write("\n")
        f.write("\n};\n")
        f.write(f"static const unsigned int fs_bin_len = {len(data)};\n")
        f.write("#endif\n")

    boot_path = 'boot/boot.bin'
    if os.path.exists(boot_path):
        with open('kernel/boot_bin.h', 'w') as f:
            f.write("/* Auto-generated by pack_fs.py */\n")
            f.write("#ifndef BOOT_BIN_H\n#define BOOT_BIN_H\n\n")
            f.write("static const unsigned char boot_bin[] = {\n")
            with open(boot_path, 'rb') as boot_f:
                data = boot_f.read()
            for idx, val in enumerate(data):
                f.write(f"0x{val:02x}, ")
                if (idx + 1) % 12 == 0:
                    f.write("\n")
            f.write("\n};\n")
            f.write(f"static const unsigned int boot_bin_len = {len(data)};\n")
            f.write("#endif\n")
        print("Generated C header files for direct RAM deployment.")

if __name__ == '__main__':
    pack_fs('programs', 'fs.bin')