name: Build inpsos IMG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: os

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib

    - name: Compile and Build IMG
      run: make

    - name: Upload IMG Artifact
      uses: actions/upload-artifact@v4
      with:
        name: inpsos-img
        path: os/inpsos.img